services:
  django:
    build: .
    container_name: matchmaker-django
    ports:
      - 8000:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static:/app/static
    environment:
      - SECRET_KEY="${SECRET_KEY}"

  nginx:
    build: ./nginx
    container_name: matchmaker-nginx
    volumes:
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django

  certbot:
    image: certbot/certbot:v2.8.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static:
