services:
  django:
    container_name: matchmaker-django
    build:
      context: .
      target: django
    ports:
      - 8000:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    restart: unless-stopped

  nginx:
    container_name: matchmaker-nginx
    build:
      context: .
      target: nginx
    volumes:
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    restart: unless-stopped
