# Generated by Django 5.0 on 2023-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("D", "Done"), ("C", "Cancelled")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
