# Generated by Django 5.0 on 2023-12-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oof_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
