# Generated by Django 5.0 on 2023-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_item_oof_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='oof_size',
        ),
    ]
